/* ===========================================================================
 * SAMPLE DATA — the entire demo dataset for the whole year
 * ===========================================================================
 * This is the "database" of the prototype. When the app starts, the store
 * (lib/store.tsx) loads everything exported here into memory. Change a value
 * here and the whole app reflects it after a refresh.
 *
 * WHAT'S IN THIS FILE, top to bottom:
 *   roles ............... the four access levels
 *   positions/simulators  pulled from the DIM reference data (lib/dim)
 *   exercises ........... the courses delivered, built from the DIM course list
 *   qualifications ...... assessor/OJTI/restriction tags + the rules that use
 *                         them (which quals a position requires/excludes)
 *   staffValidity ....... each person's currency per position
 *   leaveRecords ........ year-to-date leave
 *   trainingSessions .... training scattered across the year + attendance
 *   otherTasks .......... non-simulator commitments (meetings, courses…)
 *   runs ................ every scheduled simulator session for the year
 *   runAssignments ...... who sits which seat — generated by a mini scheduler
 *                         that obeys the SAME rules the live app enforces
 *   publicHolidays, slotTimes, auditLogs, users, importHistory …
 *
 * COMMONLY CHANGED PARAMETERS (all clearly marked "CHANGEABLE" below):
 *   - MAX_EXPIRED: how many expired-currency records to seed.
 *   - leave spells per person, training frequency, other-task counts.
 *   - the run scheduling year and how aggressively seats get filled.
 * Most generators use makeRng(seed) so the data is random-looking but the SAME
 * every reload — change a seed number to reshuffle that section.
 * =========================================================================== */
import type {
  Assignment,
  AuditAction,
  AuditLog,
  Course,
  Exercise,
  ExerciseQualRule,
  ImportHistory,
  LeaveRecord,
  OtherTask,
  Position,
  NotificationRecord,
  PositionQualRule,
  PublicHoliday,
  Qualification,
  Role,
  Run,
  RunAssignment,
  Simulator,
  SlotTime,
  Staff,
  StaffQualification,
  StaffValidity,
  TrainingAttendance,
  TrainingLogEntry,
  TrainingSession,
  User,
  FaultLog,
  FaultSeverity,
  FaultStatus,
  OperatorLog,
  OperatorLogCategory,
  FirewallLog,
  FirewallAction,
  AdminLog,
  AdminLogAction,
} from "./types"
import { addDaysISO, todayISO, parseISO, daysBetween, computeValidity } from "./dates"
import { dimPositions, dimSimulators, dimCourseList, dimRoster, dimAssignments } from "./dim"
import { TRAINING_GROUPS } from "./training-groups"
import { seededStartYear, currentYear as retentionCurrentYear } from "./retention"

const T = todayISO()

// Seed copy of the editable OJTI position groups (admins can edit these on the
// DIM Lists page; this is only the starting set for a brand-new store).
export const trainingGroups = TRAINING_GROUPS

// ── 5-year retention window ──────────────────────────────────────────────
// Data is generated for every year from HISTORY_START_YEAR up to the current
// year, so the app ships with a full rolling history (see lib/retention.ts).
// Past years are thinned to keep the durable Blob snapshot a sensible size.
const CURRENT_YEAR = retentionCurrentYear()
const HISTORY_START_YEAR = seededStartYear() // one year older than the live window
const HISTORY_START = `${HISTORY_START_YEAR}-01-01`
const HISTORY_END = `${CURRENT_YEAR}-12-31`

// Date-anchored records use a YEAR-INFIXED id (e.g. `run-2023-42`) so historical
// records can be merged into an existing saved snapshot — whose current-year
// records use the legacy `run-42` scheme — without any id collisions. The
// history-backfill migration relies on this namespace to stay idempotent.
const datedId = (prefix: string, iso: string, seq: number) => `${prefix}-${iso.slice(0, 4)}-${seq}`

export const roles: Role[] = [
  { code: "SP", level: 1, name: "Sim Pilot", description: "Level 1 – view & basic planning" },
  { code: "SUP", level: 2, name: "Supervisor", description: "Level 2 – edit runs & assignments" },
  { code: "SOO", level: 3, name: "Simulator Operational Officer", description: "Level 3 – operational officer (supervisor baseline)" },
  { code: "STO", level: 4, name: "Simulator Training Officer", description: "Level 4 – training officer (supervisor baseline)" },
  { code: "TL", level: 5, name: "Team Lead", description: "Level 5 – confirm/cancel, override" },
  { code: "Admin", level: 6, name: "Administrator", description: "Level 6 – full system control" },
]

// Two spare, fully-editable positions per program (RADAR & TOWER). These are
// generic seats teams can rename (code / name / description) and attach to any
// exercise on demand — they carry stable ids so a migration can guarantee they
// exist for both fresh installs and previously-saved snapshots.
export const flexPositions: Position[] = [
  {
    id: "pos-flex-radar-1",
    code: "FLX-R1",
    name: "Flexible Radar Position 1",
    description: "Spare radar seat — rename and attach to exercises as requirements dictate.",
    validityDays: 60,
    program: "RADAR",
    category: "Flexible",
    active: true,
    sortOrder: 900,
  },
  {
    id: "pos-flex-radar-2",
    code: "FLX-R2",
    name: "Flexible Radar Position 2",
    description: "Spare radar seat — rename and attach to exercises as requirements dictate.",
    validityDays: 60,
    program: "RADAR",
    category: "Flexible",
    active: true,
    sortOrder: 901,
  },
  {
    id: "pos-flex-tower-1",
    code: "FLX-T1",
    name: "Flexible Tower Position 1",
    description: "Spare tower seat — rename and attach to exercises as requirements dictate.",
    validityDays: 60,
    program: "TOWER",
    category: "Flexible",
    active: true,
    sortOrder: 900,
  },
  {
    id: "pos-flex-tower-2",
    code: "FLX-T2",
    name: "Flexible Tower Position 2",
    description: "Spare tower seat — rename and attach to exercises as requirements dictate.",
    validityDays: 60,
    program: "TOWER",
    category: "Flexible",
    active: true,
    sortOrder: 901,
  },
]

// Positions & simulators come from the DIM dataset, plus the spare flex seats.
export const positions: Position[] = [...dimPositions, ...flexPositions]
export const simulators: Simulator[] = dimSimulators

// Exercises delivered — [program, simulatorId, course code, required staff].
// Courses ending in " V" are validation deliveries (isValidation = true).
// Sourced from the active DIM dataset.
//
// The raw DIM list repeats the same code across different simulators/headcounts,
// which would produce multiple exercises sharing one name. Every exercise name
// must be unique, so we collapse the list to the FIRST row per (program + code).
const rawCourseList: [string, string, string, number][] = dimCourseList
const seenCourseKeys = new Set<string>()
const courseList: [string, string, string, number][] = rawCourseList.filter((row) => {
  const key = `${row[0]}|${row[2].trim().toUpperCase()}`
  if (seenCourseKeys.has(key)) return false
  seenCourseKeys.add(key)
  return true
})

export const exercises: Exercise[] = courseList.map(([program, simulatorId, code, requiredStaff], i) => {
  const isValidation = / V$/.test(code)
  const baseName = code.replace(/ V$/, "").trim()
  const programPositions = positions.filter((p) => p.program === program)
  // Named seats for this delivery. Rather than always taking the SAME first N
  // positions (which would leave later-sorted positions like AIR / GMC / OSS
  // never scheduled and therefore never "sat"), rotate the window of required
  // positions per exercise. Over the year every position gets delivered, so
  // everyone builds real currency on every position they hold — no orphaned
  // "never sat" seats. Headcount (requiredStaff) still equals the seat count.
  const n = Math.min(requiredStaff, programPositions.length)
  const start = (i * 3) % Math.max(1, programPositions.length)
  const requiredPositions = Array.from(
    { length: n },
    (_, k) => programPositions[(start + k) % programPositions.length].id,
  )
  return {
    id: `ex-${i + 1}`,
    code,
    name: isValidation ? `${baseName} Validation` : baseName,
    program,
    description: isValidation
      ? `Validation delivery of ${baseName}.`
      : `${baseName} course delivery.`,
    durationMin: 120,
    simulatorId,
    requiredStaff: n,
    isValidation,
    requiredPositions,
    active: true,
  }
})

export const qualifications: Qualification[] = [
  { id: "q-asr", code: "ASSESSOR", name: "Assessor", effect: "allow", description: "Can assess trainees during runs." },
  { id: "q-ojti", code: "OJTI", name: "On-the-Job Training Instructor", effect: "allow", description: "Can instruct on live position." },
  { id: "q-tti", code: "TTI", name: "Theoretical Training Instructor", effect: "allow", description: "Can deliver classroom training." },
  { id: "q-simb", code: "SIM-B-CERT", name: "Bravo Sim Certified", effect: "allow", description: "Certified on Approach Sim Bravo." },
  { id: "q-lvp", code: "LVP", name: "Low Visibility Endorsed", effect: "allow", description: "Endorsed for LVP exercises." },
  { id: "q-restr", code: "TEMP-RESTR", name: "Temporary Restriction", effect: "restrict", description: "Temporary medical/admin restriction." },
  { id: "q-excl-dir", code: "EXCL-DIR", name: "Director Exclusion", effect: "restrict", description: "Excluded from Director position." },
]

// ── Assignment categories (leave, duties, training, roster codes) ────────
// Sourced from the DIM dataset.
export const assignments: Assignment[] = dimAssignments

// Roster — each entry is [full name, three-letter code, role], all in the
// same sorted order. Name code maps to `initials`, role maps to `rank`.
// Sourced from the DIM dataset.
const roster: [string, string, string][] = dimRoster

// Department position pools used to split the roster cleanly in two.
const towerPositionPool = positions.filter((p) => p.program === "TOWER")
const radarPositionPool = positions.filter((p) => p.program === "RADAR")
// Deterministic rng (makeRng is a hoisted function declaration, so it is safe to
// call here even though it is defined further down) — keeps the random subset of
// covered positions stable across reloads and between server/client renders.
const staffRng = makeRng(91051)

export const staff: Staff[] = roster.map(([name, code, role], i) => {
  const parts = name.trim().split(/\s+/)
  const fn = parts[0]
  const ln = parts.slice(1).join(" ")

  // Split the roster down the middle: the first half work TOWER, the second
  // half work RADAR. Each person is operational on MOST of their department's
  // positions (a random 70–100% subset), so the department is well covered.
  const program: "TOWER" | "RADAR" = i < Math.ceil(roster.length / 2) ? "TOWER" : "RADAR"
  const pool = program === "TOWER" ? towerPositionPool : radarPositionPool

  // Fisher–Yates shuffle so the subset is uniformly random but deterministic.
  const shuffled = [...pool]
  for (let j = shuffled.length - 1; j > 0; j--) {
    const r = Math.floor(staffRng() * (j + 1))
    ;[shuffled[j], shuffled[r]] = [shuffled[r], shuffled[j]]
  }
  const minCount = Math.max(1, Math.ceil(pool.length * 0.7))
  const count = minCount + Math.floor(staffRng() * (pool.length - minCount + 1))
  const homePositions = Array.from(new Set(shuffled.slice(0, count).map((p) => p.id)))

  return {
    id: `staff-${i + 1}`,
    initials: code,
    firstName: fn,
    lastName: ln,
    rank: role,
    email: `${name.toLowerCase().replace(/[^a-z]+/g, ".").replace(/^\.|\.$/g, "")}@simcenter.aero`,
    phone: `+971 5${String(500000000 + i * 13717).slice(0, 9)}`,
    homePositions,
    programs: [program],
    active: true,
    joined: `20${15 + (i % 8)}-0${1 + (i % 8)}-1${i % 9}`,
    notes: undefined,
  }
})

// Users are derived from the active staff roster so names/emails always match
// the current DIM dataset (no hard-coded confidential names here).
const userSpecs: [number, User["role"], boolean, string][] = [
  [0, "SP", true, `${T} 07:42`],
  [3, "SUP", true, `${T} 06:58`],
  [9, "TL", true, `${T} 08:15`],
  [7, "Admin", true, `${T} 05:30`],
  [12, "SP", true, `${addDaysISO(T, -1)} 16:20`],
  [20, "SUP", false, `${addDaysISO(T, -9)} 11:05`],
  // Simulator Operational Officers (SOO, Level 3) and Simulator Training
  // Officers (STO, Level 4) — a couple of each so the new roles appear in staff
  // lists, the admin user table and role filters out of the box.
  [5, "SOO", true, `${T} 07:05`],
  [17, "SOO", true, `${addDaysISO(T, -2)} 15:48`],
  [11, "STO", true, `${T} 06:40`],
  [24, "STO", true, `${addDaysISO(T, -3)} 09:12`],
]
export const users: User[] = userSpecs.map(([idx, role, active, lastLogin], i) => {
  const s = staff[idx]
  return {
    id: `u-${i + 1}`,
    name: `${s.firstName} ${s.lastName}`,
    email: s.email,
    role,
    staffId: s.id,
    active,
    lastLogin,
  }
})

const slotList = ["08:00", "11:00", "14:00", "16:30"]

// Small deterministic PRNG (mulberry32) so the random sample data is stable
// across reloads while still looking organically spread out.
function makeRng(seed: number) {
  let a = seed >>> 0
  return () => {
    a = (a + 0x6d2b79f5) | 0
    let t = Math.imul(a ^ (a >>> 15), 1 | a)
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296
  }
}

// ── Seasonal demand curve (quarterly) ────────────────────────────────────
// Activity changes QUARTER by QUARTER, not week by week. Each calendar year is
// assigned one busy (high) quarter, one quiet (low) quarter, and two medium
// quarters — but WHICH quarter is which is randomized per year, and each year
// also gets an overall factor so some years run slow and some run intense. The
// result is a smooth seasonal wave with a single yearly peak and trough that
// still varies believably from year to year. Deterministic (seeded by year),
// so server and client agree and reloads are stable.
const QUARTER_LEVEL = { high: 0.85, med: 0.45, low: 0.16 }

interface YearProfile {
  levels: [number, number, number, number] // intensity at each quarter's centre
}
const yearProfileCache = new Map<number, YearProfile>()
function yearProfile(year: number): YearProfile {
  const cached = yearProfileCache.get(year)
  if (cached) return cached
  // Distinct deterministic RNG per year.
  const rng = makeRng((0x9e3779b1 ^ Math.imul(year, 2654435761)) >>> 0)
  // Pick the high and (distinct) low quarter; the rest are medium.
  const highQ = Math.floor(rng() * 4) % 4
  let lowQ = Math.floor(rng() * 4) % 4
  while (lowQ === highQ) lowQ = Math.floor(rng() * 4) % 4
  // Overall year factor: ~0.8 (slow year) … ~1.15 (intense year).
  const factor = 0.8 + rng() * 0.35
  const levels = [0, 1, 2, 3].map((q) => {
    const base = q === highQ ? QUARTER_LEVEL.high : q === lowQ ? QUARTER_LEVEL.low : QUARTER_LEVEL.med
    return Math.min(1, base * factor)
  }) as [number, number, number, number]
  const profile: YearProfile = { levels }
  yearProfileCache.set(year, profile)
  return profile
}

function smoothstep(t: number): number {
  const x = Math.max(0, Math.min(1, t))
  return x * x * (3 - 2 * x)
}

// Returns 0 (deep lean) … 1 (peak) for a given date, interpolating smoothly
// between the four quarter-centre levels so the wave has one clear peak/trough.
function seasonalIntensity(iso: string): number {
  const y = Number(iso.slice(0, 4))
  const { levels } = yearProfile(y)
  const dayOfYear = daysBetween(`${y}-01-01`, iso)
  const yearLen = daysBetween(`${y}-01-01`, `${y + 1}-01-01`)
  const frac = yearLen > 0 ? Math.min(0.999, dayOfYear / yearLen) : 0
  const centers = [0.125, 0.375, 0.625, 0.875]
  if (frac <= centers[0]) return levels[0]
  if (frac >= centers[3]) return levels[3]
  for (let i = 0; i < 3; i++) {
    if (frac >= centers[i] && frac < centers[i + 1]) {
      const t = smoothstep((frac - centers[i]) / (centers[i + 1] - centers[i]))
      return levels[i] + (levels[i + 1] - levels[i]) * t
    }
  }
  return levels[3]
}

// ── Courses ────────────────────────────────────────────────────────────────
// A Course groups several exercises into a multi-week delivery that needs a
// fixed headcount for its whole duration. Built from the seeded exercises with
// a FIXED rng so the demo set is the same every reload (and matches between
// server and client), while still looking random with intentional overlaps.
// These are fully editable at runtime via the store (and persisted locally).
// SIM-bucket assignment for every generated course (SIM Operational vs SIM
// Non-Operational). Populated inside the courses IIFE below and exported so the
// exercise sheet's tree is fully filled out from a fresh seed. Alternated within
// each course group so both buckets stay populated under both branches.
const courseSimClassSeed: Record<string, "operational" | "non-operational"> = {}

export const courses: Course[] = (() => {
  const rng = makeRng(73108)
  const pick = <X,>(arr: X[]): X => arr[Math.floor(rng() * arr.length)]
  const pickSome = <X,>(arr: X[], n: number): X[] => {
    const copy = [...arr]
    const out: X[] = []
    for (let i = 0; i < n && copy.length > 0; i++) {
      out.push(copy.splice(Math.floor(rng() * copy.length), 1)[0])
    }
    return out
  }
  const names = ["Alpha", "Bravo", "Charlie", "Delta", "Echo", "Foxtrot", "Golf", "Hotel", "India", "Juliet", "Kilo", "Lima"]
  const trainingThemes = ["Refresher", "Conversion", "Recurrent", "Unit Familiarisation", "Emergency Procedures", "LVP Training"]
  const validationThemes = ["Competency Check", "Annual Revalidation", "Rating Renewal", "Unit Endorsement", "Assessment Board", "Skill Validation"]
  const out: Course[] = []
  let seq = 1
  let nameIdx = 0

  // Alternate bucket assignment so SIM Operational and SIM Non-Operational each
  // receive courses within every group (keeps all four tree cells populated).
  const assignBucket = (courseId: string, i: number) => {
    courseSimClassSeed[courseId] = i % 2 === 0 ? "operational" : "non-operational"
  }

  // Generate the same course structure for EVERY retained year (history +
  // current) so the Yearly Gantt is populated under past years too, not just the
  // current year. Dates are re-anchored to each year and ids are year-infixed for
  // uniqueness; the shared rng stream keeps it deterministic yet varied per year.
  for (let year = HISTORY_START_YEAR; year <= CURRENT_YEAR; year++) {
    const yearStart = `${year}-01-01`
    for (const program of ["RADAR", "TOWER"] as const) {
      const pool = exercises.filter((e) => e.program === program)
      if (pool.length === 0) continue
      // Validation is kept SEPARATE from normal: normal + training courses draw
      // only from non-validation exercises, and validation courses draw only from
      // validation exercises, so each course sits under exactly one tree branch.
      const normalPool = pool.filter((e) => !e.isValidation)
      const validationPool = pool.filter((e) => e.isValidation)
      const normSrc = normalPool.length ? normalPool : pool
      const valSrc = validationPool.length ? validationPool : pool
      const prefix = program === "RADAR" ? "RAD" : "TWR"

      // CHANGEABLE: 10 multi-week exercise courses per program (NORMAL exercises),
      // staggered across the whole year with jitter + overlaps so it looks organic.
      const exCourses = 10
      for (let i = 0; i < exCourses; i++) {
        const slot = Math.floor((i / exCourses) * 48) // even spread Wk 1–48
        const startWeek = Math.min(50, 1 + slot + Math.floor(rng() * 5)) // + jitter
        const lengthWeeks = 4 + Math.floor(rng() * 7) // 4–10 weeks
        const startDate = addDaysISO(yearStart, (startWeek - 1) * 7)
        const endDate = addDaysISO(startDate, lengthWeeks * 7 - 1)
        const exCount = 2 + Math.floor(rng() * 4) // 2–5 exercises
        const id = `course-${year}-${seq}`
        out.push({
          id,
          code: `${prefix}-C${i + 1}`,
          name: `${program} Course ${names[nameIdx++ % names.length]}`,
          program,
          kind: "exercise",
          exerciseIds: pickSome(normSrc, Math.min(exCount, normSrc.length)).map((e) => e.id),
          startDate,
          endDate,
          requiredPeople: 4 + Math.floor(rng() * 9), // 4–12 people
          active: true,
        })
        assignBucket(id, i)
        seq++
      }

      // CHANGEABLE: 6 shorter training courses per program (NORMAL exercises).
      const trCourses = 6
      for (let i = 0; i < trCourses; i++) {
        const slot = Math.floor(((i + 0.5) / trCourses) * 48) // offset spread
        const startWeek = Math.min(51, 1 + slot + Math.floor(rng() * 4))
        const lengthWeeks = 1 + Math.floor(rng() * 4) // 1–4 weeks
        const startDate = addDaysISO(yearStart, (startWeek - 1) * 7)
        const endDate = addDaysISO(startDate, lengthWeeks * 7 - 1)
        const id = `course-${year}-${seq}`
        out.push({
          id,
          code: `${prefix}-T${i + 1}`,
          name: `${program} ${pick(trainingThemes)}`,
          program,
          kind: "training",
          exerciseIds: pickSome(normSrc, Math.min(1 + Math.floor(rng() * 2), normSrc.length)).map((e) => e.id),
          startDate,
          endDate,
          requiredPeople: 3 + Math.floor(rng() * 6), // 3–8 people
          active: true,
        })
        assignBucket(id, i)
        seq++
      }

      // CHANGEABLE: 6 validation courses per program (VALIDATION exercises only),
      // kept as their own group so they populate the tree's Validation branch.
      const vCourses = 6
      for (let i = 0; i < vCourses; i++) {
        const slot = Math.floor(((i + 0.25) / vCourses) * 48) // offset spread
        const startWeek = Math.min(51, 1 + slot + Math.floor(rng() * 4))
        const lengthWeeks = 1 + Math.floor(rng() * 3) // 1–3 weeks
        const startDate = addDaysISO(yearStart, (startWeek - 1) * 7)
        const endDate = addDaysISO(startDate, lengthWeeks * 7 - 1)
        const exCount = 1 + Math.floor(rng() * 3) // 1–3 validation exercises
        const id = `course-${year}-${seq}`
        out.push({
          id,
          code: `${prefix}-V${i + 1}`,
          name: `${program} Validation ${validationThemes[i % validationThemes.length]}`,
          program,
          kind: "exercise",
          exerciseIds: pickSome(valSrc, Math.min(exCount, valSrc.length)).map((e) => e.id),
          startDate,
          endDate,
          requiredPeople: 3 + Math.floor(rng() * 5), // 3–7 people
          active: true,
        })
        assignBucket(id, i)
        seq++
      }
    }
  }
  return out
})()

// SIM-bucket assignments for the seeded courses (see courseSimClassSeed above).
export const courseSimClass: Record<string, "operational" | "non-operational"> = courseSimClassSeed

// ── Staff qualifications ─────────────────────────────────────────────────
// Defined up-front because the run scheduler below uses them to enforce the
// qualification rules (excluded / required quals) when seating staff.
export const staffQualifications: StaffQualification[] = [
  { id: "sq-1", staffId: "staff-1", qualificationId: "q-ojti" },
  { id: "sq-2", staffId: "staff-1", qualificationId: "q-simb" },
  { id: "sq-3", staffId: "staff-2", qualificationId: "q-asr" },
  { id: "sq-4", staffId: "staff-3", qualificationId: "q-ojti" },
  { id: "sq-5", staffId: "staff-3", qualificationId: "q-tti" },
  { id: "sq-6", staffId: "staff-3", qualificationId: "q-lvp" },
  { id: "sq-7", staffId: "staff-4", qualificationId: "q-asr" },
  { id: "sq-8", staffId: "staff-4", qualificationId: "q-tti" },
  { id: "sq-9", staffId: "staff-5", qualificationId: "q-lvp" },
  { id: "sq-10", staffId: "staff-8", qualificationId: "q-restr", expiry: addDaysISO(T, 10) },
  { id: "sq-11", staffId: "staff-12", qualificationId: "q-excl-dir" },
  { id: "sq-12", staffId: "staff-6", qualificationId: "q-simb" },
  { id: "sq-13", staffId: "staff-9", qualificationId: "q-lvp" },
]

// ── Qualification rules ─────────────────────────────────────────────────
export const positionQualRules: PositionQualRule[] = [
  { id: "pqr-dir", positionId: "pos-dir", requiredQuals: [], preferredQuals: ["q-ojti"], excludedQuals: ["q-excl-dir"], allowExpiredWithWarning: true, allowManualOverride: true },
  { id: "pqr-min", positionId: "pos-min", requiredQuals: ["q-lvp"], preferredQuals: [], excludedQuals: ["q-restr"], allowExpiredWithWarning: false, allowManualOverride: true },
  { id: "pqr-amr", positionId: "pos-amr", requiredQuals: [], preferredQuals: ["q-simb"], excludedQuals: ["q-restr"], allowExpiredWithWarning: true, allowManualOverride: true },
]

export const exerciseQualRules: ExerciseQualRule[] = [
  { id: "eqr-3", exerciseId: "ex-3", requiredQuals: ["q-lvp"], preferredQuals: [], excludedQuals: [] },
  { id: "eqr-9", exerciseId: "ex-9", requiredQuals: [], preferredQuals: ["q-ojti"], excludedQuals: ["q-restr"] },
]

// ── Validity per staff/position ──────────────────��──────────────────────
// Rules enforced here:
//  • Everyone is VALID on at least their first 3 home positions.
//  • Only a small, capped number of EXPIRED records exist across the whole
//    roster, each on a different person.
//  • A small number of records are EXPIRING soon (≤14 days remaining).
//  • Remaining extra positions stay valid.
// NOTE: a completed run refreshes currency, so the numbers here are only a
// starting point — the authoritative team-wide caps are enforced by the
// normalization pass AFTER run assignments are seeded (see further below).
const MAX_EXPIRED = 2 // CHANGEABLE: how many "expired currency" records to seed across everyone
let expiredBudget = MAX_EXPIRED
export const staffValidity: StaffValidity[] = []
staff.forEach((s, si) => {
  s.homePositions.forEach((posId, k) => {
    const p = positions.find((pp) => pp.id === posId)
    if (!p) return
    const vd = p.validityDays
    let lastDateSat: string | null
    if (k < 3) {
      // Guaranteed valid: sat recently, leaving plenty of currency remaining.
      const ago = (si * 3 + k * 7) % Math.max(5, Math.floor(vd / 3))
      lastDateSat = addDaysISO(T, -ago) // daysRemaining = vd - ago (well above 14)
    } else {
      // Extra positions: seed a tiny, capped number of expired records and
      // leave everyone else comfortably valid. (Completed-run refresh below
      // reshapes this, and the normalization pass enforces the final caps.)
      const r = (si + k) % 7
      if (r === 0 && expiredBudget > 0) {
        expiredBudget--
        lastDateSat = addDaysISO(T, -(vd + 5 + (si % 10))) // past expiry → expired
      } else {
        lastDateSat = addDaysISO(T, -((si + k) % Math.max(5, Math.floor(vd / 3)))) // valid
      }
    }
    staffValidity.push({
      staffId: s.id,
      positionId: p.id,
      lastDateSat,
      validityDays: vd,
    })
  })
})

// ── Leave (full calendar span, including FUTURE planned leave) ───────────
// Every retained year — including the CURRENT year — gets a full Jan–Dec span,
// so the app carries realistic upcoming/planned leave through 31 Dec of the
// current year (surfaced by the dashboard "Upcoming Leave" panel and the leave
// calendar). Historical leave stays "approved"-heavy; future leave is a
// believable mix of approved + pending requests. Leave is generated BEFORE run
// assignments and the scheduler skips anyone on non-rejected leave, so future
// leave never collides with a seated run.
const leaveTypes: LeaveRecord["type"][] = ["Annual", "Sick", "Course", "Training", "Compassionate"]
export const leaveRecords: LeaveRecord[] = []
{
  const rng = makeRng(0x1eaf2026)
  let lvSeq = 1
  // One pass per seeded year, every year spanning the full Jan–Dec calendar so
  // both history AND forward planning are populated.
  for (let year = HISTORY_START_YEAR; year <= CURRENT_YEAR; year++) {
    const yearStart = `${year}-01-01`
    const yearEnd = `${year}-12-31`
    const span = daysBetween(yearStart, yearEnd) // days available this year
    if (span < 1) continue
    staff.forEach((s) => {
      const spells = 1 + Math.floor(rng() * 3) // CHANGEABLE: 1–3 leave spells per person / year
      for (let k = 0; k < spells; k++) {
        // Mild bias toward LEAN periods: sample TWO candidate start days and keep
        // the quieter one. This is only a gentle nudge (best of 2), so leave
        // still spreads across the WHOLE year — including the second half — which
        // keeps forward-looking "upcoming leave" populated instead of clustering
        // everything into the single leanest stretch (a stronger bias did).
        let startDate = addDaysISO(yearStart, Math.floor(rng() * span))
        const cand = addDaysISO(yearStart, Math.floor(rng() * span))
        if (seasonalIntensity(cand) < seasonalIntensity(startDate)) {
          startDate = cand
        }
        let endDate = addDaysISO(startDate, Math.floor(rng() * 5)) // 0–4 extra days
        if (endDate > yearEnd) endDate = yearEnd // clamp within the year
        const fullDay = rng() > 0.2
        const approval: LeaveRecord["approval"] = rng() > 0.15 ? "approved" : rng() > 0.5 ? "pending" : "rejected"
        leaveRecords.push({
          id: datedId("lv", startDate, lvSeq++),
          staffId: s.id,
          type: leaveTypes[Math.floor(rng() * leaveTypes.length)],
          startDate,
          endDate,
          fullDay,
          approval,
          notes: !fullDay ? "Half day" : undefined,
        })
      }
    })
  }
}

// ── Training sessions (random working days across the whole year) ────────
// Sessions are scattered on random Mon–Fri working days from Jan to Dec so
// the training calendar has activity all year round.
const trainingTypeTitles: [string, string][] = [
  ["Initial Sector Validation", "Approach Radar Sector Validation"],
  ["Initial Sector Validation", "Tower Sector Validation"],
  ["Annual COC", "Annual Competency Check"],
  ["Annual COC", "Annual COC — Emergency Procedures"],
  ["Remedial Training", "Remedial — Radar Separation"],
  ["Remedial Training", "Remedial — RT Phraseology"],
  ["Continuation Training", "Continuation — LVP Procedures"],
  ["Continuation Training", "Continuation — Threat & Error Management"],
]
// Sessions before today are marked "completed" (with attendance recorded),
// sessions today or later are "scheduled". Each session enrols an instructor
// plus 2–5 trainees drawn from the staff roster.
export const trainingSessions: TrainingSession[] = []
export const trainingAttendance: TrainingAttendance[] = []
{
  const rng = makeRng(0x5ab12026)
  let trSeq = 1
  let taSeq = 1
  for (let date = HISTORY_START; date <= HISTORY_END; date = addDaysISO(date, 1)) {
    // Generate through the end of the current year, INCLUDING future dates, so
    // the app has upcoming/scheduled training (shown on the dashboard "Upcoming
    // Training" panel and the Gantt). Past dates become "completed"; today and
    // later become "scheduled" via the isPast branch below.
    const dow = parseISO(date).getDay()
    if (dow === 0 || dow === 6) continue // working days only (Mon–Fri)
    // Seasonal: training clusters around the busy campaigns too, so the
    // Training trend line peaks in step with runs. The same curve is applied to
    // every year, so past years match the current year's shape and volume.
    const hostChance = 0.05 + 0.32 * seasonalIntensity(date) // ~5% lean … ~37% peak
    if (rng() > hostChance) continue
    const [type, title] = trainingTypeTitles[Math.floor(rng() * trainingTypeTitles.length)]
    const instructorIdx = Math.floor(rng() * staff.length)
    const instructor = staff[instructorIdx]
    const withSim = rng() > 0.4
    const sim = simulators[Math.floor(rng() * simulators.length)]
    const isPast = date < T
    const sessionId = datedId("tr", date, trSeq++)
    trainingSessions.push({
      id: sessionId,
      title,
      type,
      date,
      slotTime: slotList[Math.floor(rng() * slotList.length)],
      instructorId: instructor.id,
      simulatorId: withSim && sim ? sim.id : undefined,
      notes: trSeq % 6 === 0 ? "Mandatory annual." : undefined,
      status: isPast ? "completed" : "scheduled",
    })
    // Enrol 2–5 trainees (never the instructor) for this session.
    const traineeCount = 2 + Math.floor(rng() * 4)
    const used = new Set<number>([instructorIdx])
    for (let k = 0; k < traineeCount; k++) {
      let idx = Math.floor(rng() * staff.length)
      let guard = 0
      while (used.has(idx) && guard < staff.length) {
        idx = (idx + 1) % staff.length
        guard++
      }
      if (used.has(idx)) break
      used.add(idx)
      trainingAttendance.push({
        id: datedId("ta", date, taSeq++),
        sessionId,
        staffId: staff[idx].id,
        // Past sessions: most trainees attended; future sessions: not yet.
        attended: isPast ? rng() > 0.12 : false,
      })
    }
  }
}

// ── Other tasks (non-simulator commitments across the whole year) ��────────
// While a task runs, every assigned person is busy and is excluded from
// exercises and Fill Positions for the task's date range. These are seeded
// BEFORE run assignments so the scheduler never seats a person who is
// committed to a task that day.
// ── OJTI training log (daily on-the-job records per trainee) ──────────────
// Instructors (OJTI-qualified staff) log a trainee's daily OJT: the position
// group worked, hours trained, a performance rating and written feedback.
// Seeded across recent weekdays so the log opens with realistic history.
export const trainingLogs: TrainingLogEntry[] = []
{
  const OJTI_QUAL = "q-ojti"
  const GROUP_CAP = 40 // hours of OJT per group before validation (extension possible)
  const strengthsPool = [
    "Strong traffic picture and confident phraseology throughout.",
    "Good separation planning and early conflict detection.",
    "Clear, concise R/T and well-structured coordination.",
    "Maintained situational awareness under increasing complexity.",
    "Prioritised effectively and used silent periods to plan ahead.",
  ]
  const improvePool = [
    "Tighten sequencing on the final; a couple of gaps were larger than needed.",
    "Coordinate handoffs slightly earlier during peak inbound flows.",
    "Watch readback discipline when workload spikes.",
    "Build a more proactive plan for departures against the arrival stream.",
    "Verbalise the plan sooner so intentions are clear to the coordinator.",
  ]
  const remarkPool = [
    "Good session overall — steady, measurable progress.",
    "Solid consolidation day. Ready to progress complexity next block.",
    "Debriefed scenarios in full; trainee receptive to feedback.",
    "Recommend one more session at this level before assessment.",
    "Confidence building well; keep reinforcing the basics.",
  ]

  // Small deterministic string hash → seed, so each (trainee, group) session
  // stream is stable across reloads yet independent of the others.
  const hashSeed = (s: string) => {
    let h = 0x811c9dc5
    for (let i = 0; i < s.length; i++) {
      h ^= s.charCodeAt(i)
      h = Math.imul(h, 0x01000193)
    }
    return h >>> 0
  }

  // ── Designate an OJTI bench per program ──────────────────────────────────
  // Keep any hand-authored OJTIs (staff-1, staff-3 …) and top each program up
  // to at least three instructors so both RADAR and TOWER have a trainer bench.
  const seededOjti = new Set(
    staffQualifications.filter((q) => q.qualificationId === OJTI_QUAL).map((q) => q.staffId),
  )
  const ojtiByProgram: Record<"RADAR" | "TOWER", Staff[]> = { RADAR: [], TOWER: [] }
  for (const program of ["TOWER", "RADAR"] as const) {
    const inProgram = staff.filter((s) => s.programs.includes(program))
    const chosen: Staff[] = inProgram.filter((s) => seededOjti.has(s.id))
    for (let k = 0; k < inProgram.length && chosen.length < 3; k++) {
      if (!chosen.some((c) => c.id === inProgram[k].id)) chosen.push(inProgram[k])
    }
    ojtiByProgram[program] = chosen
  }
  const ojtiStaffIds = new Set([...ojtiByProgram.RADAR, ...ojtiByProgram.TOWER].map((s) => s.id))

  // Requirement: anyone who instructs must hold the OJTI qualification. Backfill
  // it for every designated OJTI that wasn't already hand-authored above.
  for (const id of ojtiStaffIds) {
    if (!seededOjti.has(id)) {
      staffQualifications.push({ id: `sq-ojti-${id}`, staffId: id, qualificationId: OJTI_QUAL })
    }
  }

  // ── Complete trainee coverage ────────────────────────────────────────────
  // Every non-OJTI staff member is a trainee and must show accumulated hours on
  // EVERY position group of their program. ~1 in 4 groups is fully validated
  // (≥40h, occasionally an approved extension); the rest are still in progress,
  // so the staff page and the OJTI tab both show a realistic mix.
  let logSeq = 1
  const trainees = staff.filter((s) => !ojtiStaffIds.has(s.id))
  for (const trainee of trainees) {
    const program = trainee.programs[0] as "RADAR" | "TOWER"
    const ojtis = ojtiByProgram[program]
    if (ojtis.length === 0) continue
    const groups = TRAINING_GROUPS.filter((g) => g.program === program)
    for (let gi = 0; gi < groups.length; gi++) {
      const group = groups[gi]
      const rng = makeRng(hashSeed(`${trainee.id}:${group.id}`))
      const completed = rng() < 0.25
      const target = completed
        ? GROUP_CAP + Math.round(rng() * 12) // 40–52h (may include an approved extension)
        : Math.round((4 + rng() * 32) * 2) / 2 // 4–36h in 0.5h steps (in progress)
      let remaining = target
      let dayCursor = 20 + gi * 9 + Math.floor(rng() * 15) // stagger groups over time
      let ojtiRot = Math.floor(rng() * ojtis.length)
      let guard = 0
      while (remaining > 0.01 && guard++ < 60) {
        // Advance to the next weekday.
        let date = addDaysISO(T, -dayCursor)
        let dow = parseISO(date).getDay()
        while (dow === 0 || dow === 6) {
          dayCursor++
          date = addDaysISO(T, -dayCursor)
          dow = parseISO(date).getDay()
        }
        const chunk = Math.min(remaining, Math.round((2 + rng() * 3) * 2) / 2) // 2–5h
        const ojti = ojtis[ojtiRot % ojtis.length]
        ojtiRot++
        // Train 1–2 of the group's positions.
        const shuffled = [...group.positionIds].sort(() => rng() - 0.5)
        const positionIds = shuffled.slice(0, 1 + Math.floor(rng() * Math.min(2, shuffled.length)))
        const rating = 2 + Math.floor(rng() * 4) // 2–5
        trainingLogs.push({
          id: datedId("tlog", date, logSeq++),
          date,
          program,
          groupId: group.id,
          positionIds,
          ojtiId: ojti.id,
          traineeId: trainee.id,
          hours: chunk,
          rating,
          strengths: strengthsPool[Math.floor(rng() * strengthsPool.length)],
          areasToImprove: improvePool[Math.floor(rng() * improvePool.length)],
          feedback: remarkPool[Math.floor(rng() * remarkPool.length)],
          createdAt: `${date}T17:00:00.000Z`,
        })
        remaining -= chunk
        dayCursor += 3 + Math.floor(rng() * 6) // 3–8 days between sessions
      }
    }
  }
}

const taskTitles: [string, string][] = [
  ["Safety management system review", "Quarterly SMS documentation review and hazard log update."],
  ["Recurrent first-aid course", "Mandatory recurrent first-aid certification (external provider)."],
  ["Procedures working group", "Drafting updated procedures ahead of the season."],
  ["Unit familiarisation visit", "Familiarisation visit to the operational unit."],
  ["Documentation & manuals update", "Reviewing and updating unit training manuals."],
  ["Audit preparation", "Preparing evidence packs for the upcoming regulatory audit."],
  ["OJT mentoring block", "On-the-job training mentoring and competency sign-off."],
  ["Roster planning workshop", "Workshop to build the next quarter's roster."],
  ["Equipment acceptance testing", "Acceptance testing for newly installed sim equipment."],
  ["Incident review board", "Review board for a reported operational occurrence."],
]
const taskRooms = ["Briefing Room A", "Training Centre", "Meeting Room 2", "Ops Room", "Conference Room"]
export const otherTasks: OtherTask[] = []
{
  const rng = makeRng(0x70a5c0de)
  let otSeq = 100
  for (let year = HISTORY_START_YEAR; year <= CURRENT_YEAR; year++) {
    for (let m = 0; m < 12; m++) {
      const tasksThisMonth = 1 + Math.floor(rng() * 2) // CHANGEABLE: 1–2 other-tasks per month
      for (let k = 0; k < tasksThisMonth; k++) {
        const day = 1 + Math.floor(rng() * 27)
        const startDate = `${year}-${String(m + 1).padStart(2, "0")}-${String(day).padStart(2, "0")}`
        // Future-dated tasks ARE generated (through 31 Dec of the current year) so
        // the planner/dashboard show upcoming non-simulator commitments too.
        const dow = parseISO(startDate).getDay()
        if (dow === 0 || dow === 6) continue // working days only
        const span = Math.floor(rng() * 2) // 0–1 extra days
        const endDate = addDaysISO(startDate, span)
        const count = 1 + Math.floor(rng() * 3) // 1–3 staff
        const ids = new Set<string>()
        let guard = 0
        while (ids.size < count && guard < 50) {
          ids.add(staff[Math.floor(rng() * staff.length)].id)
          guard++
        }
        const [title, description] = taskTitles[Math.floor(rng() * taskTitles.length)]
        otherTasks.push({
          id: datedId("ot", startDate, otSeq++),
          title,
          description,
          staffIds: Array.from(ids),
          startDate,
          startTime: "09:00",
          endDate,
          endTime: span ? "16:00" : "12:00",
          durationMin: span ? 480 : 180,
          classroom: taskRooms[Math.floor(rng() * taskRooms.length)],
          program: rng() > 0.5 ? "RADAR" : "TOWER",
        })
      }
    }
  }
  // A few tasks anchored around "today" so the daily planner / dashboard demo
  // always has live commitments to show.
  otherTasks.push(
    {
      id: "ot-1",
      title: "Safety management system review",
      description: "Quarterly SMS documentation review and hazard log update.",
      staffIds: ["staff-2", "staff-5"],
      startDate: T,
      startTime: "09:00",
      endDate: T,
      endTime: "12:00",
      durationMin: 180,
      classroom: "Briefing Room A",
      program: "RADAR",
    },
    {
      id: "ot-2",
      title: "Recurrent first-aid course",
      description: "Mandatory recurrent first-aid certification (external provider).",
      staffIds: ["staff-3"],
      startDate: addDaysISO(T, 1),
      startTime: "08:30",
      endDate: addDaysISO(T, 2),
      endTime: "16:30",
      durationMin: 480,
      classroom: "Training Centre",
    },
    {
      id: "ot-3",
      title: "Procedures working group",
      description: "Drafting updated low-visibility procedures ahead of the winter season.",
      staffIds: ["staff-8", "staff-9"],
      startDate: addDaysISO(T, 3),
      startTime: "13:00",
      endDate: addDaysISO(T, 3),
      endTime: "15:30",
      durationMin: 150,
      classroom: "Meeting Room 2",
      program: "TOWER",
    },
  )
}

// ── Runs across the full planning year (Jan 1 – Dec 31, current year) ────
// Every working day (Mon–Fri, weekends excluded) is seeded with exercises
// for BOTH programs — Radar (RADAR) and Tower (TOWER) — so each sim has
// activity throughout the year. Statuses are derived relative to "today":
// past days are completed/cancelled, today is confirmed/tentative, future
// days rotate through the planning statuses.
const futureStatuses: Run["status"][] = ["confirmed", "tentative", "tentative", "confirmed", "postponed"]
// Separate exercise pools per program so every working day schedules both.
const radarExercises = exercises.filter((e) => e.program === "RADAR")
const towerExercises = exercises.filter((e) => e.program === "TOWER")
const programPools: { pool: Exercise[]; cursor: number }[] = [
  { pool: radarExercises, cursor: 0 },
  { pool: towerExercises, cursor: 0 },
]
export const runs: Run[] = []
let runSeq = 1
{
  const runRng = makeRng(0x5eed12) // deterministic fill of quiet-season days
  // Per-year program balance: RADAR carries the full day's volume, while TOWER
  // schedules a year-varying fraction of it. This makes the two simulators'
  // utilization diverge (and their trend lines cross year to year) instead of
  // sitting on top of each other. CHANGEABLE: the 0.5–0.9 band controls how far
  // TOWER trails RADAR each year.
  const towerYearWeight: Record<number, number> = {}
  {
    const wRng = makeRng(0x704e1207)
    for (let y = HISTORY_START_YEAR; y <= CURRENT_YEAR; y++) towerYearWeight[y] = 0.5 + wRng() * 0.4
  }
  for (let date = HISTORY_START; date <= HISTORY_END; date = addDaysISO(date, 1)) {
    const dow = parseISO(date).getDay() // 0 = Sun … 6 = Sat
    // Working days only: Monday (1) through Friday (5).
    if (dow === 0 || dow === 6) continue
    const offset = daysBetween(T, date) // <0 past, 0 today, >0 future
    // Seasonal volume (identical every year, so past years match the current
    // year): busy campaigns run 2 concurrent sessions per program, shoulder
    // periods run 1, and deep-lean spells are mostly quiet. This gives each
    // year the requested 2–3 major spikes with clear lean troughs between.
    const intensity = seasonalIntensity(date)
    let runsToday: number
    if (intensity > 0.55) runsToday = 2
    else if (intensity > 0.22) runsToday = 1
    else runsToday = runRng() < 0.3 ? 1 : 0 // quiet season → mostly no runs
    if (runsToday === 0) continue
    let slotIndex = 0
    for (let pgIdx = 0; pgIdx < programPools.length; pgIdx++) {
      const pg = programPools[pgIdx]
      if (pg.pool.length === 0) continue
      // RADAR (index 0) runs the full day's volume; TOWER (index 1) runs a
      // year-varying fraction so the two sims accrue clearly different hours.
      let progRuns = runsToday
      if (pgIdx === 1) {
        const w = towerYearWeight[parseISO(date).getFullYear()] ?? 0.7
        let kept = 0
        for (let r = 0; r < runsToday; r++) if (runRng() < w) kept++
        progRuns = kept
      }
      for (let r = 0; r < progRuns; r++) {
        const ex = pg.pool[pg.cursor % pg.pool.length]
        pg.cursor++
        let status: Run["status"]
        if (offset < 0) status = runSeq % 7 === 0 ? "cancelled" : "completed"
        else if (offset === 0) status = r === 0 ? "confirmed" : "tentative"
        else status = futureStatuses[(runSeq + r) % futureStatuses.length]
        runs.push({
          id: datedId("run", date, runSeq),
          date,
          slotTime: slotList[slotIndex % slotList.length],
          simulatorId: ex.simulatorId,
          exerciseId: ex.id,
          status,
          requiredPositions: ex.requiredPositions,
          requiredStaff: ex.requiredStaff,
          notes: runSeq % 8 === 0 ? "Includes trainee under assessment." : undefined,
          cancellationReason: status === "cancelled" ? "Simulator hardware fault" : undefined,
          statusChangedBy:
            status === "confirmed" || status === "cancelled" ? `${staff[7].firstName} ${staff[7].lastName}` : undefined,
          statusChangedAt: status === "confirmed" || status === "cancelled" ? `${date} 09:30` : undefined,
        })
        runSeq++
        slotIndex++
      }
    }
  }
}

// ── Run assignments (scheduled through the SAME rules the app enforces) ───
// For every required seat the scheduler picks the best eligible staff member,
// mirroring the store's Fill Positions logic exactly:
//   • active, belongs to the run's program, has the position as a home position
//   • not already seated elsewhere in the same run (one position per run)
//   • not seated in another run in the same date+slot (no double-booking)
//   • not on leave (any non-rejected leave) that day
//   • not in training that day (as trainee OR instructor)
//   • not committed to another task that day
//   • currency on the position is not expired/never (enforced for today &
//     future runs; relaxed for past runs so history stays fully staffed)
//   • passes the position's qualification rule (no excluded, has all required)
// Priority: expiring currency first (to refresh before lapse), then soonest
// expiry, with a preferred-qual nudge and a fair-workload tiebreak. Some seats
// on non-completed runs are intentionally left open to show incomplete plans.
export const runAssignments: RunAssignment[] = []
{
  // Lookup maps mirroring the store's selectors.
  const validitySeedMap = new Map<string, { lastDateSat: string | null; validityDays: number }>()
  staffValidity.forEach((v) => validitySeedMap.set(`${v.staffId}:${v.positionId}`, { lastDateSat: v.lastDateSat, validityDays: v.validityDays }))

  const qualsByStaff = new Map<string, string[]>()
  staffQualifications.forEach((sq) => {
    const arr = qualsByStaff.get(sq.staffId) ?? []
    arr.push(sq.qualificationId)
    qualsByStaff.set(sq.staffId, arr)
  })

  // training busy: `${staffId}|${date}` for both trainees and instructors.
  const busyTraining = new Set<string>()
  trainingSessions.forEach((t) => busyTraining.add(`${t.instructorId}|${t.date}`))
  trainingAttendance.forEach((a) => {
    const sess = trainingSessions.find((t) => t.id === a.sessionId)
    if (sess) busyTraining.add(`${a.staffId}|${sess.date}`)
  })

  const onLeaveSeed = (staffId: string, date: string) =>
    leaveRecords.some(
      (l) => l.staffId === staffId && l.approval !== "rejected" && date >= l.startDate && date <= l.endDate,
    )
  const onTaskSeed = (staffId: string, date: string) =>
    otherTasks.some((t) => t.staffIds.includes(staffId) && date >= t.startDate && date <= t.endDate)
  // Currency is measured as-of the run's OWN date (not today) so the historical
  // scheduler behaves like it would have on the day: once a person sits a
  // position their currency resets, so they stop being the top pick and seats
  // rotate around the eligible pool instead of clustering on one person.
  const validityStatusSeed = (staffId: string, posId: string, ref: string) => {
    const v = validitySeedMap.get(`${staffId}:${posId}`)
    if (!v) return { status: "never" as const, daysRemaining: null as number | null }
    const c = computeValidity(v.lastDateSat, v.validityDays, ref)
    return { status: c.status, daysRemaining: c.daysRemaining }
  }

  let asgSeq = 1
  let overrideCount = 0
  const MAX_OVERRIDES = 3 // CHANGEABLE: how many TL-approved manual overrides to seed
  const slotBusy = new Map<string, Set<string>>() // date|slot -> staffIds seated
  const workload = new Map<string, number>() // fairness across the whole year
  const posLoad = new Map<string, number>() // `${staffId}|${posId}` -> times sat that exact position (drives rotation)

  for (const run of runs) {
    const ex = exercises.find((e) => e.id === run.exerciseId)
    const program = ex?.program ?? "RADAR"
    const isPast = daysBetween(T, run.date) < 0
    const slotKey = `${run.date}|${run.slotTime}`
    if (!slotBusy.has(slotKey)) slotBusy.set(slotKey, new Set())
    const busySlot = slotBusy.get(slotKey)!
    const assignedThisRun = new Set<string>()

    run.requiredPositions.forEach((posId, pi) => {
      // CHANGEABLE: leave roughly 1 in 5 seats open on non-completed runs to
      // simulate incomplete plans. The "% 5 === 4" is the 1-in-5; raise the 5
      // to fill more seats, or remove this to fill every eligible seat.
      const leaveOpen = run.status !== "completed" && (asgSeq + pi) % 5 === 4
      const rule = positionQualRules.find((r) => r.positionId === posId)
      let chosenId: string | null = null
      let override = false
      let overrideReason: string | undefined

      if (!leaveOpen) {
        const cands: { id: string; score: number; load: number }[] = []
        for (const s of staff) {
          if (!s.active) continue
          if (!s.programs.includes(program)) continue
          if (!s.homePositions.includes(posId)) continue
          if (assignedThisRun.has(s.id)) continue
          if (busySlot.has(s.id)) continue
          if (onLeaveSeed(s.id, run.date)) continue
          if (busyTraining.has(`${s.id}|${run.date}`)) continue
          if (onTaskSeed(s.id, run.date)) continue
          const sq = qualsByStaff.get(s.id) ?? []
          if (rule) {
            if (rule.excludedQuals.some((q) => sq.includes(q))) continue
            if (rule.requiredQuals.some((q) => !sq.includes(q))) continue
          }
          // Past runs: judge currency as-of the run day (drives rotation).
          // Today/future runs: judge as-of today, matching the live app's gate.
          const v = validityStatusSeed(s.id, posId, isPast ? run.date : T)
          if (!isPast && (v.status === "expired" || v.status === "never")) continue
          let score = v.daysRemaining ?? 999
          if (v.status === "expiring") score -= 1000 // expiring outranks merely-valid
          if (rule?.preferredQuals.some((q) => sq.includes(q))) score -= 5
          // Rotation: the more times this person has already sat THIS position,
          // the lower they rank for it, so seats rotate around the eligible pool
          // instead of one person owning a position all year.
          score += (posLoad.get(`${s.id}|${posId}`) ?? 0) * 30
          cands.push({ id: s.id, score, load: workload.get(s.id) ?? 0 })
        }
        cands.sort((a, b) => a.score - b.score || a.load - b.load || (a.id < b.id ? -1 : 1))
        const pick = cands[0]
        if (pick) {
          chosenId = pick.id
          // Sprinkle a few TL-approved overrides on future seats to keep the
          // manual-override feature populated (still an eligible candidate).
          if (!isPast && overrideCount < MAX_OVERRIDES && asgSeq % 53 === 0) {
            override = true
            overrideReason = "Operational necessity – TL approved"
            overrideCount++
          }
        }
      }

      if (chosenId) {
        assignedThisRun.add(chosenId)
        busySlot.add(chosenId)
        workload.set(chosenId, (workload.get(chosenId) ?? 0) + 1)
        posLoad.set(`${chosenId}|${posId}`, (posLoad.get(`${chosenId}|${posId}`) ?? 0) + 1)
        // A COMPLETED run is a real, delivered session, so it refreshes the
        // person's currency on that position. Runs are seeded in chronological
        // order, so the LAST completed run per staff+position ends up as their
        // true "last date sat" — making the profile Validity tab and Run History
        // always agree. Cancelled/postponed runs never happened, so they never
        // refresh currency.
        if (run.status === "completed") {
          const key = `${chosenId}:${posId}`
          const cur = validitySeedMap.get(key)
          if (cur) validitySeedMap.set(key, { ...cur, lastDateSat: run.date })
        }
      }
      runAssignments.push({
        id: datedId("asg", run.date, asgSeq++),
        runId: run.id,
        positionId: posId,
        staffId: chosenId,
        manualOverride: override || undefined,
        overrideReason,
      })
    })
  }

  // Sync the derived "last date sat" back into the exported validity records so
  // every profile's Validity tab shows the EXACT date of the person's most
  // recent completed run on that position — matching their Run History — rather
  // than an unrelated random date. Positions never sat in a completed run keep
  // their seeded baseline (so currency still varies: valid / expiring / expired).
  for (const v of staffValidity) {
    const derived = validitySeedMap.get(`${v.staffId}:${v.positionId}`)
    if (derived) v.lastDateSat = derived.lastDateSat
  }
}

// ── Currency-warning caps (authoritative) ────────────────────────────────
// The completed-run sync above can leave a position reading as expiring or
// expired whenever it was last sat before a quiet spell — which, across the
// whole roster, adds up to a noisy dashboard. For a clean demo we keep only a
// small, fixed number of expiring + expired records team-wide and refresh
// everything else to comfortably valid. Deterministic (stable sort), so the
// exact same records are shown every reload. Valid/never records are untouched,
// so the vast majority of profiles still show their real last-sat date.
{
  const TARGET_EXPIRED = 2 // CHANGEABLE: expired-currency records team-wide (kept minimal)
  const TARGET_EXPIRING = 3 // CHANGEABLE: expiring-soon records team-wide (kept minimal)
  let keepExpired = TARGET_EXPIRED
  let keepExpiring = TARGET_EXPIRING
  const ordered = [...staffValidity].sort((a, b) =>
    `${a.staffId}:${a.positionId}` < `${b.staffId}:${b.positionId}` ? -1 : 1,
  )
  for (const v of ordered) {
    const status = computeValidity(v.lastDateSat, v.validityDays).status
    if (status === "expired" && keepExpired > 0) {
      keepExpired--
      continue
    }
    if (status === "expiring" && keepExpiring > 0) {
      keepExpiring--
      continue
    }
    if (status === "expired" || status === "expiring") {
      // Over the team-wide budget → refresh to comfortably valid (well outside
      // the 14-day warning window).
      v.lastDateSat = addDaysISO(T, -Math.max(1, Math.floor(v.validityDays / 4)))
    }
  }
}

// ── Currency top-up (authoritative for the LIVE app) ─────────────────────
// The store derives every person's currency from their COMPLETED run history
// (see validityMap in lib/store.tsx), NOT from the seeded staffValidity dates
// above — so with the quarterly volume curve some held positions naturally drift
// into expiring/expired by "today" (e.g. when the current year's low quarter
// falls early). To keep conflicts and currency alerts at the requested minimum,
// we seed a recent "revalidation" completed run for each lapsing held position,
// leaving only a small handful of alerts for realism. Deterministic (stable
// sort), so the same records show every reload.
{
  const KEEP_EXPIRED = 2 // CHANGEABLE: expired alerts left on the live dashboard
  const KEEP_EXPIRING = 3 // CHANGEABLE: expiring alerts left on the live dashboard
  const staffByIdMap = new Map(staff.map((s) => [s.id, s]))
  const posByIdMap = new Map(positions.map((p) => [p.id, p]))
  const runByIdMap = new Map(runs.map((r) => [r.id, r]))
  // Most-recent completed run per staff:position — mirrors the store exactly.
  const lastSat = new Map<string, string>()
  for (const a of runAssignments) {
    if (!a.staffId) continue
    const r = runByIdMap.get(a.runId)
    if (!r || r.status !== "completed" || r.date > T) continue
    const k = `${a.staffId}:${a.positionId}`
    const prev = lastSat.get(k)
    if (!prev || r.date > prev) lastSat.set(k, r.date)
  }
  // Deterministically ordered list of lapsing HELD combos (active staff only).
  const lapsing: { staffId: string; posId: string; status: "expired" | "expiring" }[] = []
  for (const [k, date] of [...lastSat.entries()].sort((a, b) => (a[0] < b[0] ? -1 : 1))) {
    const [staffId, posId] = k.split(":")
    const s = staffByIdMap.get(staffId)
    if (!s || !s.active || !s.homePositions.includes(posId)) continue
    const p = posByIdMap.get(posId)
    if (!p) continue
    const st = computeValidity(date, p.validityDays, T).status
    if (st === "expired" || st === "expiring") lapsing.push({ staffId, posId, status: st })
  }
  // Refresh all but a small kept remainder by appending a completed revalidation
  // run dated a few days ago (well inside every validity window → reads valid).
  let keepE = KEEP_EXPIRED
  let keepG = KEEP_EXPIRING
  let topupSeq = 1
  for (const { staffId, posId, status } of lapsing) {
    if (status === "expired" && keepE > 0) {
      keepE--
      continue
    }
    if (status === "expiring" && keepG > 0) {
      keepG--
      continue
    }
    const s = staffByIdMap.get(staffId)!
    const program = s.programs[0] ?? "RADAR"
    const ex =
      exercises.find((e) => e.program === program && e.requiredPositions.includes(posId)) ??
      exercises.find((e) => e.program === program) ??
      exercises[0]
    const date = addDaysISO(T, -(5 + (topupSeq % 10))) // 5–14 days ago, spread out
    const runId = datedId("run", date, 900000 + topupSeq)
    runs.push({
      id: runId,
      date,
      slotTime: slotList[topupSeq % slotList.length],
      simulatorId: ex.simulatorId,
      exerciseId: ex.id,
      status: "completed",
      requiredPositions: [posId],
      requiredStaff: 1,
      notes: "Currency revalidation session.",
    })
    runAssignments.push({
      id: datedId("asg", date, 900000 + topupSeq),
      runId,
      positionId: posId,
      staffId,
    })
    // Keep the raw staffValidity export consistent with the run-derived view.
    const rec = staffValidity.find((v) => v.staffId === staffId && v.positionId === posId)
    if (rec) rec.lastDateSat = date
    topupSeq++
  }
}

// ── Public holidays ─────────────────────────────────────────────────────
const year = new Date(T).getFullYear()
// Public holidays for EVERY retained year (history + current) so the calendar,
// leave planner and working-day calculations have holidays across the whole
// 2021→current span, not just the current year. (Month/day are approximated as
// fixed for simplicity; that is fine for a demo calendar.)
const holidayDefs: [string, string][] = [
  ["01-01", "New Year's Day"],
  ["04-18", "Good Friday"],
  ["05-04", "Early May Bank Holiday"],
  ["05-25", "Spring Bank Holiday"],
  ["06-15", "Founders Day"],
  ["08-31", "Summer Bank Holiday"],
  ["12-25", "Christmas Day"],
  ["12-26", "Boxing Day"],
]
export const publicHolidays: PublicHoliday[] = (() => {
  const out: PublicHoliday[] = []
  for (let y = HISTORY_START_YEAR; y <= CURRENT_YEAR; y++) {
    holidayDefs.forEach(([md, name], i) => {
      out.push({ id: `ph-${y}-${i + 1}`, date: `${y}-${md}`, name })
    })
  }
  return out
})()

export const slotTimes: SlotTime[] = [
  { id: "st-1", label: "Morning 1", startTime: "08:00", endTime: "10:30" },
  { id: "st-2", label: "Morning 2", startTime: "11:00", endTime: "13:00" },
  { id: "st-3", label: "Afternoon 1", startTime: "14:00", endTime: "16:00" },
  { id: "st-4", label: "Afternoon 2", startTime: "16:30", endTime: "18:30" },
]

// Audit log user names are derived from staff so no confidential names leak.
const auditName = (idx: number) => `${staff[idx].firstName} ${staff[idx].lastName}`
const firstExCode = exercises[0]?.code ?? "EX"

// A continuous audit trail across EVERY retained year, so the admin Activity /
// audit view is populated with history from 2021 onward — not just the last few
// days. The most recent days keep the hand-written entries below; earlier years
// are filled with a believable, deterministic spread of administrative actions.
export const auditLogs: AuditLog[] = (() => {
  const rng = makeRng(0xa0d17)
  const out: AuditLog[] = []
  const templates: { action: AuditAction; detail: (i: number) => string }[] = [
    { action: "exercise.confirm", detail: (i) => `Confirmed run RUN-${100 + i} (${firstExCode})` },
    { action: "exercise.cancel", detail: () => "Cancelled a run – reason: Simulator hardware fault" },
    { action: "assignment.change", detail: () => "Reassigned a position on a scheduled run" },
    { action: "assignment.override", detail: () => "Manual override applied (expired validity)" },
    { action: "leave.edit", detail: (i) => `Approved annual leave for ${auditName(i % staff.length)}` },
    { action: "qualification.edit", detail: (i) => `Updated endorsements for ${auditName(i % staff.length)}` },
    { action: "excel.import", detail: (i) => `Imported schedule_wk${10 + (i % 40)}.xlsx` },
    { action: "staff.edit", detail: (i) => `Edited staff profile for ${auditName(i % staff.length)}` },
    { action: "course.edit", detail: () => "Adjusted course date range" },
    { action: "permission.change", detail: (i) => `Changed ${auditName(i % staff.length)} role` },
  ]
  let seq = 100
  // ~10 entries per historical year, spread month-to-month.
  for (let y = HISTORY_START_YEAR; y < CURRENT_YEAR; y++) {
    for (let k = 0; k < 10; k++) {
      const month = 1 + Math.floor(rng() * 12)
      const day = 1 + Math.floor(rng() * 27)
      const hh = String(8 + Math.floor(rng() * 9)).padStart(2, "0")
      const mm = String(Math.floor(rng() * 60)).padStart(2, "0")
      const t = templates[Math.floor(rng() * templates.length)]
      out.push({
        id: `al-${y}-${seq}`,
        timestamp: `${y}-${String(month).padStart(2, "0")}-${String(day).padStart(2, "0")} ${hh}:${mm}`,
        user: auditName(Math.floor(rng() * staff.length)),
        action: t.action,
        detail: t.detail(seq),
      })
      seq++
    }
  }
  // Recent hand-written entries (current year, last few days).
  out.push(
    { id: "al-1", timestamp: `${T} 09:32`, user: auditName(7), action: "exercise.confirm", detail: `Confirmed run RUN-22 (${firstExCode})` },
    { id: "al-2", timestamp: `${T} 08:50`, user: auditName(3), action: "assignment.change", detail: "Assigned trainee to a position on RUN-22" },
    { id: "al-3", timestamp: `${addDaysISO(T, -1)} 16:11`, user: auditName(9), action: "excel.import", detail: "Imported schedule_wk24.xlsx (38 rows, 35 accepted)" },
    { id: "al-4", timestamp: `${addDaysISO(T, -1)} 14:02`, user: auditName(7), action: "exercise.cancel", detail: "Cancelled RUN-18 – reason: Simulator hardware fault" },
    { id: "al-5", timestamp: `${addDaysISO(T, -1)} 11:45`, user: auditName(9), action: "permission.change", detail: `Changed ${auditName(15)} role SP → SUP (reverted)` },
    { id: "al-6", timestamp: `${addDaysISO(T, -2)} 10:20`, user: auditName(3), action: "assignment.override", detail: "Manual override on RUN-15 (expired validity)" },
    { id: "al-7", timestamp: `${addDaysISO(T, -2)} 09:05`, user: auditName(9), action: "qualification.edit", detail: `Added LVP endorsement to ${auditName(12)}` },
    { id: "al-8", timestamp: `${addDaysISO(T, -3)} 15:30`, user: auditName(7), action: "leave.edit", detail: `Approved annual leave for ${auditName(6)}` },
  )
  return out
})()

// Import history across every retained year (roughly monthly uploads) so the
// import log is populated from 2021 onward, plus the recent hand-written rows.
export const importHistory: ImportHistory[] = (() => {
  const rng = makeRng(0x1770a7)
  const out: ImportHistory[] = []
  let seq = 100
  for (let y = HISTORY_START_YEAR; y < CURRENT_YEAR; y++) {
    for (let m = 0; m < 12; m++) {
      if (rng() > 0.75) continue // ~9 uploads/year
      const day = 1 + Math.floor(rng() * 27)
      const total = 30 + Math.floor(rng() * 20)
      const rejected = Math.floor(rng() * 6)
      const ext = rng() > 0.3 ? "xlsx" : "csv"
      out.push({
        id: `ih-${y}-${seq}`,
        filename: `schedule_${y}_wk${10 + m * 4}.${ext}`,
        date: `${y}-${String(m + 1).padStart(2, "0")}-${String(day).padStart(2, "0")}`,
        user: auditName(Math.floor(rng() * staff.length)),
        rowsTotal: total,
        rowsAccepted: total - rejected,
        rowsRejected: rejected,
      })
      seq++
    }
  }
  out.push(
    { id: "ih-1", filename: "schedule_wk24.xlsx", date: addDaysISO(T, -1), user: auditName(9), rowsTotal: 38, rowsAccepted: 35, rowsRejected: 3 },
    { id: "ih-2", filename: "schedule_wk23.xlsx", date: addDaysISO(T, -8), user: auditName(9), rowsTotal: 41, rowsAccepted: 41, rowsRejected: 0 },
    { id: "ih-3", filename: "schedule_wk22.csv", date: addDaysISO(T, -15), user: auditName(3), rowsTotal: 36, rowsAccepted: 30, rowsRejected: 6 },
  )
  return out
})()

// ── Notifications (derived history across every retained year) ───────────
// A realistic notification log so the Messages / admin Notifications views are
// never empty: training invites/reminders to enrolled staff, plus periodic
// weekly roster digests. Past notifications are marked read (mostly); future
// ones (for upcoming sessions) are unread. All are flagged `simulated` since no
// email provider runs in the demo.
export const notifications: NotificationRecord[] = (() => {
  const rng = makeRng(0x0f17)
  const out: NotificationRecord[] = []
  const sentBy = auditName(9)
  const attendeesBySession = new Map<string, string[]>()
  trainingAttendance.forEach((a) => {
    const arr = attendeesBySession.get(a.sessionId) ?? []
    arr.push(a.staffId)
    attendeesBySession.set(a.sessionId, arr)
  })
  let seq = 1
  // Training invites/reminders — sample ~every 3rd session to keep volume sane.
  trainingSessions.forEach((s, si) => {
    if (si % 3 !== 0) return
    const isPast = s.date < T
    const recipients = [s.instructorId, ...(attendeesBySession.get(s.id) ?? [])]
    recipients.forEach((staffId) => {
      const person = staff.find((p) => p.id === staffId)
      if (!person) return
      out.push({
        id: `ntf-${s.date.slice(0, 4)}-${seq++}`,
        staffId,
        channel: rng() > 0.25 ? "email" : "sms",
        kind: "training",
        subject: isPast ? `Training completed: ${s.title}` : `Training scheduled: ${s.title}`,
        body: isPast
          ? `This confirms your attendance record for "${s.title}" on ${s.date}.`
          : `You are enrolled in "${s.title}" on ${s.date} at ${s.slotTime}. Please confirm availability.`,
        to: person.email,
        sentAt: `${addDaysISO(s.date, isPast ? 0 : -3)}T${String(7 + Math.floor(rng() * 3)).padStart(2, "0")}:15:00`,
        sentBy,
        simulated: true,
        readAt: isPast && rng() > 0.2 ? `${addDaysISO(s.date, -2)}T09:40:00` : undefined,
      })
    })
  })
  // Weekly roster digests — one per active program lead-ish person each quarter.
  for (let y = HISTORY_START_YEAR; y <= CURRENT_YEAR; y++) {
    for (let q = 0; q < 4; q++) {
      const month = q * 3 + 1
      const date = `${y}-${String(month).padStart(2, "0")}-05`
      if (date > HISTORY_END) continue
      staff.slice(0, 6).forEach((person) => {
        const isPast = date < T
        out.push({
          id: `ntf-${y}-${seq++}`,
          staffId: person.id,
          channel: "email",
          kind: "weekly",
          subject: `Weekly roster — week commencing ${date}`,
          body: `Your assignments and any changes for the week starting ${date} are now published.`,
          to: person.email,
          sentAt: `${date}T06:30:00`,
          sentBy,
          simulated: true,
          readAt: isPast ? `${date}T08:05:00` : undefined,
        })
      })
    }
  }
  return out
})()

// ── Historical seed (years BEFORE the current year) ───────────────────���──────
// The single source of truth for the multi-year history. An existing saved
// snapshot only holds current-year data, so the history-backfill migration
// (lib/persisted-state.ts) injects exactly these records — matched by their
// year-infixed ids so re-running it never duplicates anything.
const isHistoricalDate = (iso: string) => Number(iso.slice(0, 4)) < CURRENT_YEAR
const historicalRunIds = new Set(runs.filter((r) => isHistoricalDate(r.date)).map((r) => r.id))
const historicalSessionIds = new Set(
  trainingSessions.filter((t) => isHistoricalDate(t.date)).map((t) => t.id),
)

// ── Fault logs ───────────────────────────────────────────────────────────────
export const faultLogs: FaultLog[] = (() => {
  const rng = makeRng(0xfa017)
  const out: FaultLog[] = []
  const systems = ["TS1 Motion Platform", "TS2 Motion Platform", "Instructor Station A", "Instructor Station B",
    "Visual System TS1", "Visual System TS2", "Network Switch Room", "Air-Con Unit SIM Hall", "UPS Bank A"]
  const severities: FaultSeverity[] = ["critical", "major", "minor", "info"]
  const statuses: FaultStatus[]     = ["open", "in-progress", "resolved", "closed"]
  const descriptions = [
    "Motion platform hydraulic pressure low — safety interlocks triggered",
    "Instructor station freeze — unresponsive to input for >2 min",
    "Visual channel 3 rendering artefacts at high bank angles",
    "UPS battery health warning on self-test",
    "Network latency spike affecting real-time data feed",
    "Air-con compressor fault — ambient temperature rising",
    "Motion DOF 4 encoder position drift detected",
    "Projector lamp hour threshold exceeded — schedule replacement",
    "Control loader torque feedback out of calibration tolerance",
    "Audio system crackling on left headset channel",
  ]
  const resolutions = [
    "Hydraulics re-primed, pressure restored. System signed off.",
    "Instructor station hard-rebooted. Monitoring for recurrence.",
    "Video card driver rolled back. Channel 3 clear.",
    "UPS battery replaced. Self-test passed.",
    "Network switch port replaced. Latency nominal.",
    "Refrigerant topped up. Ambient temperature within limits.",
    "Encoder recalibrated. DOF 4 within tolerance.",
    "Projector lamp replaced. Hours reset.",
    "Control loader recalibrated. Feedback within spec.",
    "Left headset replaced. Audio clear.",
  ]
  let seq = 1
  for (let y = HISTORY_START_YEAR; y <= CURRENT_YEAR; y++) {
    const count = 8 + Math.floor(rng() * 8)
    for (let i = 0; i < count; i++) {
      const month = 1 + Math.floor(rng() * 12)
      const day   = 1 + Math.floor(rng() * 27)
      const hh    = String(6 + Math.floor(rng() * 14)).padStart(2, "0")
      const mm    = String(Math.floor(rng() * 60)).padStart(2, "0")
      const ts    = `${y}-${String(month).padStart(2,"0")}-${String(day).padStart(2,"0")} ${hh}:${mm}`
      const sev   = severities[Math.floor(rng() * severities.length)]
      const idx   = Math.floor(rng() * descriptions.length)
      const isClosed = y < CURRENT_YEAR || rng() > 0.35
      const status: FaultStatus = isClosed ? (rng() > 0.5 ? "resolved" : "closed") : (rng() > 0.5 ? "open" : "in-progress")
      out.push({
        id: `fl-${y}-${seq}`,
        timestamp: ts,
        severity: sev,
        status,
        system: systems[Math.floor(rng() * systems.length)],
        description: descriptions[idx],
        reportedBy: auditName(Math.floor(rng() * staff.length)),
        ...(isClosed ? {
          resolvedAt: `${y}-${String(month).padStart(2,"0")}-${String(Math.min(day + 1 + Math.floor(rng() * 3), 28)).padStart(2,"0")} ${String(8 + Math.floor(rng() * 9)).padStart(2,"0")}:${String(Math.floor(rng() * 60)).padStart(2,"0")}`,
          resolution: resolutions[idx],
        } : {}),
      })
      seq++
    }
  }
  return out.sort((a, b) => b.timestamp.localeCompare(a.timestamp))
})()

// ── Operator logs ────────────────────────────────────────────────────────────
export const operatorLogs: OperatorLog[] = (() => {
  const rng = makeRng(0x0e1a7)
  const out: OperatorLog[] = []
  const shifts: OperatorLog["shift"][] = ["morning", "afternoon", "night"]
  const categories: OperatorLogCategory[] = ["briefing", "run", "handover", "incident", "maintenance", "note"]
  const entries: Record<OperatorLogCategory, string[]> = {
    briefing:    ["Morning brief complete. All sessions on schedule.", "Crew brief — TS2 SIM in maintenance hold until 1100."],
    run:         ["Run RUN-101 completed on time. No issues.", "Run RUN-102 delayed 15 min — late instructor arrival.", "Run RUN-103 terminated early — trainee unwell."],
    handover:    ["Handover to afternoon shift. TS1 motion standby. No open faults.", "Handover complete. UPS test pending 1400. Note hydraulics pressure at lower nominal."],
    incident:    ["Minor incident — trainee reported nausea during high-G profile. Run paused, trainee recovered.", "Fire panel false alarm (kitchen smoke). Cleared by facilities."],
    maintenance: ["Projector lamp replaced on TS2 visual ch2. Hours reset to 0.", "Control loader annual calibration completed. All axes within spec."],
    note:        ["Simulator hall temp 22°C. Air-con nominal.", "Visitor tour through SIM hall 1430–1515. No disruption."],
  }
  let seq = 1
  for (let y = HISTORY_START_YEAR; y <= CURRENT_YEAR; y++) {
    const count = 15 + Math.floor(rng() * 15)
    for (let i = 0; i < count; i++) {
      const month = 1 + Math.floor(rng() * 12)
      const day   = 1 + Math.floor(rng() * 27)
      const shift = shifts[Math.floor(rng() * shifts.length)]
      const hh    = shift === "morning" ? 6 + Math.floor(rng() * 6) : shift === "afternoon" ? 12 + Math.floor(rng() * 6) : 18 + Math.floor(rng() * 5)
      const mm    = Math.floor(rng() * 60)
      const cat   = categories[Math.floor(rng() * categories.length)]
      const pool  = entries[cat]
      out.push({
        id: `ol-${y}-${seq}`,
        timestamp: `${y}-${String(month).padStart(2,"0")}-${String(day).padStart(2,"0")} ${String(hh).padStart(2,"0")}:${String(mm).padStart(2,"0")}`,
        shift,
        operator: auditName(Math.floor(rng() * staff.length)),
        category: cat,
        entry: pool[Math.floor(rng() * pool.length)],
      })
      seq++
    }
  }
  return out.sort((a, b) => b.timestamp.localeCompare(a.timestamp))
})()

// ── Firewall / security device logs ──────────────────────────────────────────
export const firewallLogs: FirewallLog[] = (() => {
  const rng = makeRng(0xf1e4a)
  const out: FirewallLog[] = []
  const actions: FirewallAction[] = ["allow", "deny", "drop", "alert"]
  const protocols = ["TCP", "UDP", "ICMP"]
  const rules = ["RULE-INBOUND-01", "RULE-OUTBOUND-02", "RULE-SSH-DENY", "RULE-HTTP-ALLOW", "RULE-HTTPS-ALLOW", "RULE-SCAN-ALERT", "RULE-MGMT-ALLOW", "RULE-GEO-BLOCK"]
  const descriptions: Record<FirewallAction, string[]> = {
    allow:  ["Authorised management traffic passed", "Outbound HTTPS to approved endpoint", "Internal VLAN routing allowed"],
    deny:   ["Inbound SSH attempt from unknown host denied", "Port scan detected and blocked", "Geo-blocked region connection refused"],
    drop:   ["Malformed packet dropped at perimeter", "Flood attack mitigation — packets silently dropped", "ICMP flood suppressed"],
    alert:  ["Repeated failed auth attempts — brute force alert", "Unusual outbound data volume flagged", "Known threat-intel IP contacted"],
  }
  const ipBlock = () => `${10 + Math.floor(rng() * 235)}.${Math.floor(rng() * 255)}.${Math.floor(rng() * 255)}.${1 + Math.floor(rng() * 253)}`
  const ports   = [22, 80, 443, 3389, 8080, 5432, 1433, 53, 25, 3306]
  let seq = 1
  for (let y = HISTORY_START_YEAR; y <= CURRENT_YEAR; y++) {
    const count = 20 + Math.floor(rng() * 20)
    for (let i = 0; i < count; i++) {
      const month = 1 + Math.floor(rng() * 12)
      const day   = 1 + Math.floor(rng() * 27)
      const hh    = String(Math.floor(rng() * 24)).padStart(2, "0")
      const mm    = String(Math.floor(rng() * 60)).padStart(2, "0")
      const ss    = String(Math.floor(rng() * 60)).padStart(2, "0")
      const action = actions[Math.floor(rng() * actions.length)]
      const pool   = descriptions[action]
      out.push({
        id: `fwl-${y}-${seq}`,
        timestamp: `${y}-${String(month).padStart(2,"0")}-${String(day).padStart(2,"0")} ${hh}:${mm}:${ss}`,
        action,
        sourceIp: ipBlock(),
        destinationIp: ipBlock(),
        port: ports[Math.floor(rng() * ports.length)],
        protocol: protocols[Math.floor(rng() * protocols.length)],
        rule: rules[Math.floor(rng() * rules.length)],
        description: pool[Math.floor(rng() * pool.length)],
      })
      seq++
    }
  }
  return out.sort((a, b) => b.timestamp.localeCompare(a.timestamp))
})()

// ── Administrator logs ─────────────────────────────────���──────────────────────
export const adminLogs: AdminLog[] = (() => {
  const rng = makeRng(0xad4170)
  const out: AdminLog[] = []
  const actions: AdminLogAction[] = [
    "session.login","session.logout","session.timeout","user.create","user.edit","user.delete",
    "role.change","permission.change","config.change","backup.create","backup.restore","system.restart",
  ]
  const details: Record<AdminLogAction, (i: number) => string> = {
    "session.login":      (i) => `Login successful — ${auditName(i % staff.length)}`,
    "session.logout":     (i) => `Logout — ${auditName(i % staff.length)}`,
    "session.timeout":    (i) => `Session timed out — ${auditName(i % staff.length)} (idle >30 min)`,
    "user.create":        (i) => `New user account created for ${auditName(i % staff.length)}`,
    "user.edit":          (i) => `User profile updated — ${auditName(i % staff.length)}`,
    "user.delete":        (i) => `User account deactivated — ${auditName(i % staff.length)}`,
    "role.change":        (i) => `Role changed: ${auditName(i % staff.length)} SP → SUP`,
    "permission.change":  (i) => `Permission matrix updated by ${auditName(i % staff.length)}`,
    "config.change":      ()  => `System configuration parameter updated`,
    "backup.create":      ()  => `Automated daily backup completed successfully`,
    "backup.restore":     ()  => `Backup restored to snapshot from previous day`,
    "system.restart":     ()  => `Scheduled maintenance restart completed`,
  }
  const ipBlock = () => `192.168.${1 + Math.floor(rng() * 5)}.${10 + Math.floor(rng() * 100)}`
  let seq = 1
  for (let y = HISTORY_START_YEAR; y <= CURRENT_YEAR; y++) {
    const count = 12 + Math.floor(rng() * 10)
    for (let i = 0; i < count; i++) {
      const month = 1 + Math.floor(rng() * 12)
      const day   = 1 + Math.floor(rng() * 27)
      const hh    = String(7 + Math.floor(rng() * 12)).padStart(2, "0")
      const mm    = String(Math.floor(rng() * 60)).padStart(2, "0")
      const action = actions[Math.floor(rng() * actions.length)]
      out.push({
        id: `adl-${y}-${seq}`,
        timestamp: `${y}-${String(month).padStart(2,"0")}-${String(day).padStart(2,"0")} ${hh}:${mm}`,
        user: auditName(Math.floor(rng() * staff.length)),
        action,
        detail: details[action](seq),
        ipAddress: ipBlock(),
      })
      seq++
    }
  }
  return out.sort((a, b) => b.timestamp.localeCompare(a.timestamp))
})()

export const historicalSeed = {
  runs: runs.filter((r) => isHistoricalDate(r.date)),
  runAssignments: runAssignments.filter((a) => historicalRunIds.has(a.runId)),
  leaveRecords: leaveRecords.filter((l) => isHistoricalDate(l.startDate)),
  trainingSessions: trainingSessions.filter((t) => isHistoricalDate(t.date)),
  trainingAttendance: trainingAttendance.filter((a) => historicalSessionIds.has(a.sessionId)),
  otherTasks: otherTasks.filter((t) => isHistoricalDate(t.startDate)),
}
